apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Важно! Данные сохранятся после удаления PVC
  storageClassName: manual
  hostPath:
    path: /tmp/nfs-test

