apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    app: network         
  ports:
    - name: http
      protocol: TCP
      port: 80            # Порт внутри кластера
      targetPort: 80      # Порт контейнера nginx
      nodePort: 30080     # Внешний порт на ноде (от 30000 до 32767)