apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: network
  ports:
    - name: nginx-port
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool-port
      protocol: TCP
      port: 9002
      targetPort: 8080