apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo "$(date) - Hello from BusyBox" >> /data/shared-file.txt;
                sleep 5;
              done
          volumeMounts:
            - name: shared-data
              mountPath: /data
        - name: multitool
          image: wbitt/network-multitool
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                cat /data/shared-file.txt || echo "Waiting for file...";
                sleep 5;
              done
          volumeMounts:
            - name: shared-data
              mountPath: /data

