apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-logs-daemonset
spec:
  selector:
    matchLabels:
      app: multitool-logs
  template:
    metadata:
      labels:
        app: multitool-logs
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          command: ["/bin/sh", "-c"]
          args:
            - |
              tail -f /var/log/syslog
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory

