apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: netology  # Service будет направлять трафик на Pod с таким лейблом
  ports:
  - protocol: TCP
    port: 80       # внешний порт, на который Service слушает
    targetPort: 8080 # порт, на который перенаправляется трафик внутри Pod'а.
